version: '3.8'

services:
  app:
    build:
      context: . # O Dockerfile está no mesmo diretório
    ports:
      - "3000:80" # Mapeia a porta 3000 do host para a porta 80 do container
    volumes:
      - .:/var/www/html # Sincroniza os arquivos locais com o container
